/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Encode;
import classes.ObtenerIP;
import classes.User;
import classesDAO.LoginLogsDAO;
import classesDAO.UserDAO;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author melan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int ancho, alto;
    int posX, posY;
    //User usuario;

    Encode encrip;

    User user = new User();
    UserDAO userdao = new UserDAO();
    // Obtener la dirección IP
    ObtenerIP obtenerIP = new ObtenerIP();
    String ipAddress = obtenerIP.obtenerIP();

    int id_user;
    String nombre_user, pass_user;
    
    public Login() {
        initComponents();
       encrip = new Encode();
        //LLAMANDO A LA FUNCION PARA CENTRAR LA VENTANA
        this.centrarVentanaEnPantalla();
        
        //REDONDER LOS BORDES DE LA VENTANA
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
    }
    //MÉTODO PARA CENTRAR LA PANTALLA
    private void centrarVentanaEnPantalla() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension windowSize = getSize();
        int x = (screenSize.width - windowSize.width) / 2;
        int y = (screenSize.height - windowSize.height) / 2;
        setLocation(x, y);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTUserIN = new javax.swing.JTextField();
        jTPasswordIN = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jBIngresarSistema = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbtn_min = new javax.swing.JButton();
        jbtn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(192, 190, 186));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("Usuario: ");

        jTUserIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setText("Contraseña: ");

        jBIngresarSistema.setBackground(new java.awt.Color(0, 0, 0));
        jBIngresarSistema.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jBIngresarSistema.setForeground(new java.awt.Color(255, 255, 255));
        jBIngresarSistema.setText("Iniciar Sesión");
        jBIngresarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresarSistemaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo_login.png"))); // NOI18N

        jbtn_min.setBackground(new java.awt.Color(190, 192, 186));
        jbtn_min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_min.png"))); // NOI18N
        jbtn_min.setPreferredSize(new java.awt.Dimension(18, 18));
        jbtn_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_minActionPerformed(evt);
            }
        });

        jbtn_close.setBackground(new java.awt.Color(190, 192, 186));
        jbtn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_close.png"))); // NOI18N
        jbtn_close.setPreferredSize(new java.awt.Dimension(18, 18));
        jbtn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtn_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(128, 226, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTPasswordIN, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTUserIN, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBIngresarSistema)
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTUserIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTPasswordIN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jBIngresarSistema)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIngresarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresarSistemaActionPerformed
        String usuario = this.jTUserIN.getText();
        String password = this.jTPasswordIN.getText();
        String claveEncriptada = encrip.Encriptar(password);
        user = userdao.IngresarSistema(usuario, claveEncriptada);

        boolean ExisteUserName = false;
      
        for (int i = 0; i < userdao.ListarUsuarios().size(); i++) {
            if (usuario.equals(userdao.ListarUsuarios().get(i).getUser_name())
                    && claveEncriptada.equals(userdao.ListarUsuarios().get(i).getPassword_user())) {
                
                
                ExisteUserName = true;
                break; // Salir del bucle una vez que se encuentra una coincidencia
            }

        }

        if (ExisteUserName) {
            String rol = user.getType_user();
            if (rol.equals("Administrador")) {
                // Mostrar dashboard de administrador
                id_user = user.getUser_id();
                nombre_user = user.getFirst_name();
                pass_user = user.getPassword_user();
                Dashboard_main DashAdmin = new Dashboard_main(id_user, nombre_user, pass_user);
                this.dispose();
                DashAdmin.setVisible(true);
                JOptionPane.showMessageDialog(null, "Bienvenido Administrador: " + user.getFirst_name());

                // Insertar la dirección IP en la base de datos
                LoginLogsDAO loginLogsDAO = new LoginLogsDAO();
                loginLogsDAO.InsertarLoginLog(ipAddress, user.getUser_id());
            } else  {
                // Mostrar dashboard de usuario empleado
                id_user = user.getUser_id();
                nombre_user = user.getFirst_name();
                pass_user = user.getPassword_user();
                Dashboard_empleados DashEmpleado = new Dashboard_empleados(id_user, nombre_user, pass_user);
                this.dispose();
                DashEmpleado.setVisible(true);
                JOptionPane.showMessageDialog(null, "Bienvenido Empleado: " + user.getFirst_name());

                // Insertar la dirección IP en la base de datos
                LoginLogsDAO loginLogsDAO = new LoginLogsDAO();
                loginLogsDAO.InsertarLoginLog(ipAddress, user.getUser_id());
            }
        }
      else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.");
      }
        
    }//GEN-LAST:event_jBIngresarSistemaActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x-posX, p.y-posY);  
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        this.posX = evt.getX();
        this.posY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jbtn_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_minActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_minActionPerformed

    private void jbtn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtn_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIngresarSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jTPasswordIN;
    private javax.swing.JTextField jTUserIN;
    private javax.swing.JButton jbtn_close;
    private javax.swing.JButton jbtn_min;
    // End of variables declaration//GEN-END:variables
}
