/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelsAdmin;

import classes.Taxe;
import classesDAO.TaxeDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mario
 */
public class Panel_costos extends javax.swing.JPanel {

    Taxe taxe;
    TaxeDAO taxeDAO;
    
    //listas
    List<Taxe> lTaxe;
    
    boolean bandporcentaje;
    double porcentaje;
    DefaultTableModel model;
    
    int id;
    
    
    int id_user;
    String nombre_user, pass_user;
    
    public Panel_costos(int id, String nombre, String pass) {
        initComponents();
        bandporcentaje = false;
        porcentaje = 0;
        model = new DefaultTableModel();
        taxeDAO = new TaxeDAO();
        
        this.cargar_table();
        
        //variable para el update o delete
        id = 0;
        
        id_user = id;
        nombre_user = nombre;
        pass_user = pass;
        
        this.jLUser.setText(nombre_user);
    }
    
    void cargar_table(){
        model.setRowCount(0);
        String[] nombreColum = {"Impuesto", "Porcentaje", "Valor en decimal"};
        model.setColumnIdentifiers(nombreColum);
        
        try {
            lTaxe = taxeDAO.listarTaxe();
            
            if (lTaxe.size()>-1) {
                for (int i = 0; i < lTaxe.size(); i++) {
                    model.addRow(new Object[]{lTaxe.get(i).getNAME(), lTaxe.get(i).getPercentage(), lTaxe.get(i).getVALUE()});
                }
                this.jTableCostos.setModel(model);
                this.jTableCostos.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                this.jTableCostos.setFillsViewportHeight(true);
            }
        } catch (Exception e) {
            this.jBIngresar.setEnabled(false);
            this.jBBuscar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Error al cargar el panel de costos");
        }
    }
    
    void cargar_tableNombre(String pNombre){
        model.setRowCount(0);
        String[] nombreColum = {"Impuesto", "Porcentaje", "Valor en decimal"};
        model.setColumnIdentifiers(nombreColum);
        
        try {
            lTaxe = taxeDAO.listarTaxeNombre(pNombre);
            
            if (lTaxe.size()>-1) {
                for (int i = 0; i < lTaxe.size(); i++) {
                    model.addRow(new Object[]{lTaxe.get(i).getNAME(), lTaxe.get(i).getPercentage(), lTaxe.get(i).getVALUE()});
                }
                this.jTableCostos.setModel(model);
                this.jTableCostos.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                this.jTableCostos.setFillsViewportHeight(true);
            }
        } catch (Exception e) {
            this.jBIngresar.setEnabled(false);
            this.jBBuscar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Error al cargar el panel de costos");
        }
    }
    
    void limpiar(){
        this.jBIngresar.setEnabled(true);
        //desactivar botones
        this.jBModificar.setEnabled(false);

        this.jTNombreIN.setText("");
        this.JTPorcentajeIN.setText("");
        this.jTDecimalIN.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTNombreIN = new javax.swing.JTextField();
        JTPorcentajeIN = new javax.swing.JTextField();
        jTDecimalIN = new javax.swing.JTextField();
        jBIngresar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCostos = new javax.swing.JTable();
        jTNombreBuscar = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jLUser = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 190, 186));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(143, 5, 30));
        jLabel1.setText("Costos");

        jPanel1.setBackground(new java.awt.Color(192, 190, 186));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 5, 30), 2));

        jTNombreIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTNombreIN.setText("Ingrese el nombre del impuesto");
        jTNombreIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTNombreINMouseClicked(evt);
            }
        });

        JTPorcentajeIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JTPorcentajeIN.setText("Ingrese el porcentaje");
        JTPorcentajeIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTPorcentajeINMouseClicked(evt);
            }
        });
        JTPorcentajeIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTPorcentajeINActionPerformed(evt);
            }
        });
        JTPorcentajeIN.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JTPorcentajeINPropertyChange(evt);
            }
        });
        JTPorcentajeIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTPorcentajeINKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTPorcentajeINKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTPorcentajeINKeyTyped(evt);
            }
        });

        jTDecimalIN.setEditable(false);
        jTDecimalIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTDecimalIN.setText("Valor en decimal");

        jBIngresar.setBackground(new java.awt.Color(143, 5, 30));
        jBIngresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jBIngresar.setText("Ingresar");
        jBIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresarActionPerformed(evt);
            }
        });

        jBModificar.setBackground(new java.awt.Color(143, 5, 30));
        jBModificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBModificar.setForeground(new java.awt.Color(255, 255, 255));
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBModificar))
                    .addComponent(jTNombreIN, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addComponent(JTPorcentajeIN)
                    .addComponent(jTDecimalIN))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTNombreIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JTPorcentajeIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTDecimalIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIngresar)
                    .addComponent(jBModificar))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(192, 190, 186));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 5, 30), 2));

        jTableCostos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableCostos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCostos.setRowHeight(35);
        jTableCostos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCostosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCostos);

        jTNombreBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTNombreBuscar.setText("Ingrese el nombre del impuesto a buscar");
        jTNombreBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTNombreBuscarMouseClicked(evt);
            }
        });

        jBBuscar.setBackground(new java.awt.Color(143, 5, 30));
        jBBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLUser.setText("Bienvenido: User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(426, 426, 426))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLUser)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLUser)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTNombreINMouseClicked
        if (this.jTNombreIN.getText().equals("Ingrese el nombre del impuesto")) {
            this.jTNombreIN.setText("");
        }
    }//GEN-LAST:event_jTNombreINMouseClicked

    private void JTPorcentajeINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTPorcentajeINMouseClicked
        if (this.JTPorcentajeIN.getText().equals("Ingrese el porcentaje")) {
            this.JTPorcentajeIN.setText("");
        }
    }//GEN-LAST:event_JTPorcentajeINMouseClicked

    private void JTPorcentajeINKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTPorcentajeINKeyTyped
        
    }//GEN-LAST:event_JTPorcentajeINKeyTyped

    private void JTPorcentajeINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTPorcentajeINKeyPressed
        
    }//GEN-LAST:event_JTPorcentajeINKeyPressed

    private void JTPorcentajeINPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JTPorcentajeINPropertyChange
        
    }//GEN-LAST:event_JTPorcentajeINPropertyChange

    private void JTPorcentajeINKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTPorcentajeINKeyReleased
        double conversion = 0;
        try {
            porcentaje = Double.parseDouble(this.JTPorcentajeIN.getText().trim());
            if (porcentaje > 0 && porcentaje <101) {
                bandporcentaje = true;
                conversion = porcentaje / 100;
            }
        } catch (Exception e) {
            bandporcentaje = false;
        }
        this.jTDecimalIN.setText(String.valueOf(conversion));
    }//GEN-LAST:event_JTPorcentajeINKeyReleased

    private void jBIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresarActionPerformed
        boolean bandExiste = false;
        
        String nombreImpuesto = this.jTNombreIN.getText();
        String porcen = this.JTPorcentajeIN.getText()+"%";
        porcentaje /= 100;
        
        
        
        if (bandporcentaje) {
            if (lTaxe.size() > 0) {
                for (int i = 0; i < lTaxe.size(); i++) {
                    if (nombreImpuesto.toLowerCase().equals(lTaxe.get(i).getNAME().toLowerCase())) {
                        bandExiste = true;
                    }
                }
            }
            
            if (!bandExiste) {
                if (!nombreImpuesto.equals("Ingrese el nombre del impuesto") && nombreImpuesto.trim().length() > 0) {
                    
                    taxe = new Taxe(nombreImpuesto, porcen, porcentaje);
                
                    if (taxeDAO.insert(taxe)) {
                        JOptionPane.showMessageDialog(null, "Se ingresó el impuesto");
                        this.cargar_table();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error al ingresar el impuesto");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "No puede dejar el campo de nombre de impuesto vacio");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "El impuesto existe");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Error! El porcentaje debe estar entre 1% y 100%\n"
                                                           + "El campo de porcentaje deber ser valor numerico");
        }
    }//GEN-LAST:event_jBIngresarActionPerformed

    private void jTableCostosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCostosMouseClicked
    try {
        if(this.jTableCostos.getSelectedRow() > -1){
            //activar los botones de actualizar y eliminar
            this.jBIngresar.setEnabled(false);
            this.jBModificar.setEnabled(true);

            int index = this.jTableCostos.getSelectedRow();
            String porc = ((DefaultTableModel)this.jTableCostos.getModel()).getValueAt(index, 1).toString().replace("%", "");
            
            id = this.lTaxe.get(index).getTaxe_id();
            this.jTNombreIN.setText(((DefaultTableModel)this.jTableCostos.getModel()).getValueAt(index, 0).toString());
            
            this.JTPorcentajeIN.setText(porc);
            this.jTDecimalIN.setText(((DefaultTableModel)this.jTableCostos.getModel()).getValueAt(index, 2).toString());                
            
            porcentaje  = Double.parseDouble(porc.trim());
            bandporcentaje = true;
        }
        else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningún elemento de la tabla");
        }
    } 
    catch (Exception e) {
    }        
    }//GEN-LAST:event_jTableCostosMouseClicked

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        String nombreImpuesto = this.jTNombreIN.getText();
        String porcen = this.JTPorcentajeIN.getText()+"%";
        porcentaje /= 100;
        
        
        
        if (bandporcentaje) {
            if (!nombreImpuesto.equals("Ingrese el nombre del impuesto") && nombreImpuesto.trim().length() > 0) {

                taxe = new Taxe(id, nombreImpuesto, porcen, porcentaje);

                int response = JOptionPane.showConfirmDialog(null, "¿Desea modificar el impuesto?", "Confirmar", JOptionPane.YES_NO_OPTION);
                
                if (response == JOptionPane.YES_OPTION) {
                    if (taxeDAO.update(taxe)) {
                        JOptionPane.showMessageDialog(null, "Se modificó el impuesto");
                        this.cargar_table();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error al modificar el impuesto");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Se canceló la accción modificar el impuesto");
                }
                
            }
            else{
                JOptionPane.showMessageDialog(null, "No puede dejar el campo de nombre de impuesto vacio");
            }

        }
        else{
            JOptionPane.showMessageDialog(null, "Error! El porcentaje debe estar entre 1% y 100%\n"
                                                           + "El campo de porcentaje deber ser valor numerico");
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void JTPorcentajeINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTPorcentajeINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTPorcentajeINActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        String nombre = this.jTNombreBuscar.getText();
        
        if (!nombre.equals("") && nombre.trim().length() > 0) {
            this.cargar_tableNombre(nombre);
        }
        else{
            JOptionPane.showMessageDialog(null, "No puede dejar el campo de buscar vacio");
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTNombreBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTNombreBuscarMouseClicked
        if (this.jTNombreBuscar.getText().equals("Ingrese el nombre del impuesto a buscar")) {
            this.jTNombreBuscar.setText("");
        }
    }//GEN-LAST:event_jTNombreBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTPorcentajeIN;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBIngresar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDecimalIN;
    private javax.swing.JTextField jTNombreBuscar;
    private javax.swing.JTextField jTNombreIN;
    private javax.swing.JTable jTableCostos;
    // End of variables declaration//GEN-END:variables
}
